import type {
  CategoryNode,
  ImportReview,
  TransactionDetail,
  TransactionItem,
  TransactionList,
} from '@moneylens/types';

export const categoryTree: CategoryNode[] = [
  {
    id: 'food',
    name: 'Food',
    slug: 'food',
    parentId: null,
    color: null,
    icon: null,
    isSystem: true,
    children: [
      {
        id: 'food-delivery',
        name: 'Food Delivery',
        slug: 'food-delivery',
        parentId: 'food',
        color: null,
        icon: null,
        isSystem: true,
      },
      {
        id: 'restaurants',
        name: 'Restaurants',
        slug: 'restaurants',
        parentId: 'food',
        color: null,
        icon: null,
        isSystem: true,
      },
    ],
  },
  {
    id: 'pets',
    name: 'Pets',
    slug: 'pets',
    parentId: null,
    color: null,
    icon: null,
    isSystem: false,
    children: [],
  },
];

export const swiggy: TransactionItem = {
  id: 't1',
  date: '2026-09-05T08:30:00.000Z',
  amountPaise: 45_200,
  currency: 'INR',
  type: 'DEBIT',
  flow: 'OUT',
  merchantId: 'm1',
  merchantName: 'Swiggy',
  description: 'UPI-SWIGGY-sw•••@icici',
  category: { id: 'food', name: 'Food', slug: 'food' },
  subcategory: { id: 'food-delivery', name: 'Food Delivery', slug: 'food-delivery' },
  paymentMethod: 'UPI',
  source: 'CSV',
  status: 'CONFIRMED',
  isRecurring: false,
  notes: null,
  upiIdMasked: 'sw•••@icici',
  referenceMasked: '••••5432',
  categoryConfidence: 0.85,
};

export const salary: TransactionItem = {
  ...swiggy,
  id: 't2',
  date: '2026-09-01T06:30:00.000Z',
  amountPaise: 14_500_000,
  type: 'CREDIT',
  flow: 'IN',
  merchantId: 'm2',
  merchantName: 'Northwind',
  category: null,
  subcategory: null,
  upiIdMasked: null,
  referenceMasked: null,
};

export function transactionList(items: TransactionItem[], total = items.length): TransactionList {
  return {
    items,
    page: 1,
    pageSize: 25,
    total,
    summary: {
      incomePaise: 14_500_000,
      grossSpendingPaise: 45_200,
      refundsPaise: 0,
      spendingPaise: 45_200,
      cashbackPaise: 0,
      savedPaise: 14_454_800,
      savingsRatePct: 99.7,
      spendTransactionCount: 1,
      averageSpendPaise: 45_200,
      medianSpendPaise: 45_200,
    },
  };
}

export const swiggyDetail: TransactionDetail = {
  ...swiggy,
  sourceFile: { id: 'imp1', filename: 'hdfc.csv' },
  createdAt: '2026-10-01T00:00:00.000Z',
  updatedAt: '2026-10-01T00:00:00.000Z',
};

export const importReview: ImportReview = {
  import: {
    id: 'imp1',
    filename: 'hdfc.csv',
    source: 'CSV',
    parserName: 'csv@1',
    status: 'READY_FOR_REVIEW',
    createdAt: '2026-10-01T00:00:00.000Z',
    confirmedAt: null,
    statementStart: '2026-09-01',
    statementEnd: '2026-09-05',
    detectedCount: 2,
    duplicateCount: 1,
    committedCount: 0,
    errorMessage: null,
  },
  stats: {
    detected: 2,
    included: 1,
    excluded: 1,
    possibleDuplicates: 1,
    uncategorized: 0,
    firstDate: '2026-09-01',
    lastDate: '2026-09-05',
    totalDebitsPaise: 45_200,
    totalCreditsPaise: 0,
  },
  rows: [
    {
      id: 'r1',
      rowIndex: 5,
      date: '2026-09-05T08:30:00.000Z',
      amountPaise: 45_200,
      type: 'DEBIT',
      flow: 'OUT',
      rawDescription: 'UPI-SWIGGY',
      merchantName: 'Swiggy',
      category: { id: 'food-delivery', name: 'Food Delivery', slug: 'food-delivery' },
      categoryConfidence: 0.85,
      decision: 'INCLUDE',
      duplicateReason: null,
      warnings: [],
    },
    {
      id: 'r2',
      rowIndex: 6,
      date: '2026-09-01T06:30:00.000Z',
      amountPaise: 30_000,
      type: 'DEBIT',
      flow: 'OUT',
      rawDescription: 'UPI-ZOMATO',
      merchantName: 'Zomato',
      category: null,
      categoryConfidence: null,
      decision: 'DUPLICATE',
      duplicateReason: 'Same reference number as a transaction you already have',
      warnings: [],
    },
  ],
  warnings: ['Dates were read as day/month/year.'],
};
