import type { DashboardData } from '@moneylens/types';

export const dashboardFixture: DashboardData = {
  month: '2026-09',
  availableMonths: ['2026-07', '2026-08', '2026-09'],
  historyMonths: 2,
  totals: {
    incomePaise: 14_500_000,
    grossSpendingPaise: 9_000_000,
    refundsPaise: 0,
    spendingPaise: 9_000_000,
    cashbackPaise: 0,
    savedPaise: 5_500_000,
    savingsRatePct: 37.9,
    spendTransactionCount: 42,
    averageSpendPaise: 214_286,
    medianSpendPaise: 45_000,
  },
  comparison: {
    previousMonth: '2026-08',
    incomeChangePct: 0,
    spendingChangePct: 12.4,
    savedChangePaise: -1_000_000,
  },
  categories: [
    {
      categoryId: 'housing',
      name: 'Housing',
      slug: 'housing',
      color: null,
      amountPaise: 3_200_000,
      sharePct: 35.6,
      transactionCount: 1,
    },
    {
      categoryId: 'food',
      name: 'Food',
      slug: 'food',
      color: null,
      amountPaise: 2_500_000,
      sharePct: 27.8,
      transactionCount: 30,
    },
    {
      categoryId: 'shopping',
      name: 'Shopping',
      slug: 'shopping',
      color: null,
      amountPaise: 1_500_000,
      sharePct: 16.7,
      transactionCount: 4,
    },
    {
      categoryId: 'transport',
      name: 'Transport',
      slug: 'transport',
      color: null,
      amountPaise: 800_000,
      sharePct: 8.9,
      transactionCount: 5,
    },
    {
      categoryId: 'bills',
      name: 'Bills',
      slug: 'bills',
      color: null,
      amountPaise: 500_000,
      sharePct: 5.6,
      transactionCount: 1,
    },
    {
      categoryId: 'health',
      name: 'Healthcare',
      slug: 'healthcare',
      color: null,
      amountPaise: 300_000,
      sharePct: 3.3,
      transactionCount: 1,
    },
    {
      categoryId: 'ent',
      name: 'Entertainment',
      slug: 'entertainment',
      color: null,
      amountPaise: 120_000,
      sharePct: 1.3,
      transactionCount: 1,
    },
    {
      categoryId: 'other',
      name: 'Other',
      slug: 'other',
      color: null,
      amountPaise: 80_000,
      sharePct: 0.9,
      transactionCount: 1,
    },
  ],
  trend: [
    { month: '2026-07', incomePaise: 14_500_000, spendingPaise: 8_000_000, savedPaise: 6_500_000 },
    { month: '2026-08', incomePaise: 14_500_000, spendingPaise: 8_000_000, savedPaise: 6_500_000 },
    { month: '2026-09', incomePaise: 14_500_000, spendingPaise: 9_000_000, savedPaise: 5_500_000 },
  ],
  topMerchants: [{ merchantId: 'm1', name: 'Swiggy', amountPaise: 900_000, transactionCount: 12 }],
  observations: [
    {
      id: 'category-above-average:food-delivery',
      kind: 'OBSERVATION',
      severity: 'medium',
      title: 'Food Delivery is ₹2,100 above your 2-month average',
      explanation: 'You spent ₹9,000 on Food Delivery this month.',
      metric: { label: 'Above 2-month average', valuePaise: 210_000 },
      supportingTransactionIds: ['a', 'b', 'c'],
    },
  ],
};
